# Generated by Django 3.1.6 on 2021-02-18 22:49

from django.conf import settings
from django.db import migrations, models
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_validity_for_existing_confirmations(
    apps: StateApps, schema_editor: DatabaseSchemaEditor
) -> None:
    Confirmation = apps.get_model("confirmation", "Confirmation")
    # The values at the time of this migration
    Confirmation.USER_REGISTRATION = 1
    Confirmation.INVITATION = 2
    Confirmation.EMAIL_CHANGE = 3
    Confirmation.UNSUBSCRIBE = 4
    Confirmation.SERVER_REGISTRATION = 5
    Confirmation.MULTIUSE_INVITE = 6
    Confirmation.REALM_CREATION = 7
    Confirmation.REALM_REACTIVATION = 8
    Confirmation.objects.filter(type=Confirmation.USER_REGISTRATION).update(
        validity_in_days=settings.CONFIRMATION_LINK_DEFAULT_VALIDITY_DAYS
    )
    Confirmation.objects.filter(type=Confirmation.INVITATION).update(
        validity_in_days=settings.INVITATION_LINK_VALIDITY_DAYS
    )
    Confirmation.objects.filter(type=Confirmation.EMAIL_CHANGE).update(
        validity_in_days=settings.CONFIRMATION_LINK_DEFAULT_VALIDITY_DAYS
    )
    Confirmation.objects.filter(type=Confirmation.UNSUBSCRIBE).update(validity_in_days=1000000)
    Confirmation.objects.filter(type=Confirmation.SERVER_REGISTRATION).update(
        validity_in_days=settings.CONFIRMATION_LINK_DEFAULT_VALIDITY_DAYS
    )
    Confirmation.objects.filter(type=Confirmation.MULTIUSE_INVITE).update(
        validity_in_days=settings.INVITATION_LINK_VALIDITY_DAYS
    )
    Confirmation.objects.filter(type=Confirmation.REALM_CREATION).update(
        validity_in_days=settings.CONFIRMATION_LINK_DEFAULT_VALIDITY_DAYS
    )
    Confirmation.objects.filter(type=Confirmation.REALM_REACTIVATION).update(
        validity_in_days=settings.CONFIRMATION_LINK_DEFAULT_VALIDITY_DAYS
    )


class Migration(migrations.Migration):

    dependencies = [
        ("confirmation", "0007_add_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="validity_in_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            set_validity_for_existing_confirmations,
            elidable=True,
        ),
    ]
